# Numpy

Numpy is a library very functional because allows creating arrays. Contrary to the lists, the arrays are a type of object that optimizes operations between huge quantities of data, specifically, numeric data. In linear algebra, you use operations between matrices, vectors, and blocks of numbers that represents data of features. To aspire to be data scientist you need to get a strong knowledge in some area of mathematics, overall, linear algebra. This library is helpful to apply this knowledge of an easier way.

As data scientist you have to carry out over entire collection of value and you want to do this fast. Let's see how it works

First, and the most important we need install the library in the our system. Therefore, you must entry at your console, terminal or your bash the respective command (`pip install numpy`). If you need more information about the library, you may find it [here](http://www.numpy.org/)

    Note: Numpy is a library contained on SciPy package. Thus, don't worry if have to install SciPy in order to use Numpy.

In [16]:
import numpy

#declare a list with numeric values
list_test = [1, 2, 3]
#convert a list in a vector
array1 = numpy.array(list_test)  
# note that this is object type numpy
print(type(array1))            
#this say you what is the size of your array. In 2D arrays, the first number represents the rows and second the columns
print(array1.shape)          
#you can acces to specific element inside of your array passing the correspond index
first_element = array1[0]
print(first_element, array1[1], array1[2])  
# Also, you can change the elment in this index by assing new value
array1[0] = 5                  # Change an element of the array
print(array1)               

#also you can create an array with two rows, each square brackets represent one row
array2 = numpy.array([[1,2,3],[4,5,6]])
print(array2.shape)   

# you can acces a specific element by passing the coordenates. You could think in it as if it were a chessboard
print(array2[0, 0], array2[0, 1], array2[1, 0])   

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
[[1 2 3]
 [4 5 6]]
[[1.5 2.  3. ]
 [4.  5.  6. ]]
1 2 4


Numpy, like the anothers objets that we already saw, has atributes/methods. One of them is `shape()`. How we saw, `shape()` give youthe size of the array in each dimension. For a matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the number of axes. Moreover, there are other method used in data science. Let's see it.

* ndarray.size: the total number of elements of the array. This is equal to the product of the elements of shape.

In [13]:
print("The number of elements contained in the array1 is:", array1.size)

The number of elements contained in the array1 is: 3


To create sequences of numbers, NumPy provides a function analogous to range that returns arrays instead of lists. This is `arange` where the first parameter is the start point, the second is the final point, and the last parameter is the number of numbers that will compound the array. Furthermore, you could need create one array with different dimensions based in the above array. This function is `reshape()` where expected like parameters the size of the future matrix.

In [20]:
array1 = numpy.arange( 10, 41, 6 )
print("The elements in the array are", array1, ". This size", array1.shape )
array1 = array1.reshape(2,3)
print("The elements in the array are", array1, ". This new size is", array1.shape )

The elements in the array are [10 16 22 28 34 40] . This size (6,)
The elements in the array are [[10 16 22]
 [28 34 40]] . This new size is (2, 3)


When arange is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step:

In [21]:
print(numpy.linspace( 0, 2, 9 ))               # 9 numbers from 0 to 2
x = numpy.linspace( 0, 2*numpy.pi, 100 )        # useful to evaluate function at lots of points
f = numpy.sin(x) #make an array with the seno of each value
print(x)
print(f)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[0.         0.06346652 0.12693304 0.19039955 0.25386607 0.31733259
 0.38079911 0.44426563 0.50773215 0.57119866 0.63466518 0.6981317
 0.76159822 0.82506474 0.88853126 0.95199777 1.01546429 1.07893081
 1.14239733 1.20586385 1.26933037 1.33279688 1.3962634  1.45972992
 1.52319644 1.58666296 1.65012947 1.71359599 1.77706251 1.84052903
 1.90399555 1.96746207 2.03092858 2.0943951  2.15786162 2.22132814
 2.28479466 2.34826118 2.41172769 2.47519421 2.53866073 2.60212725
 2.66559377 2.72906028 2.7925268  2.85599332 2.91945984 2.98292636
 3.04639288 3.10985939 3.17332591 3.23679243 3.30025895 3.36372547
 3.42719199 3.4906585  3.55412502 3.61759154 3.68105806 3.74452458
 3.8079911  3.87145761 3.93492413 3.99839065 4.06185717 4.12532369
 4.1887902  4.25225672 4.31572324 4.37918976 4.44265628 4.5061228
 4.56958931 4.63305583 4.69652235 4.75998887 4.82345539 4.88692191
 4.95038842 5.01385494 5.07732146 5.14078798 5.2042545  5.26772102
 5.33118753 5.394

In data science is crucial have in mind the operations between matrix. Specially, the difference among element-wise and matricial multiplication. Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the `dot` function or method:

In [23]:
A = numpy.array( [[1,1],[0,1]] )
B = numpy.array( [[2,0],[3,4]] )
print("The multiplicacion between each element by ohter element in different matrices is obtained by A * B",A * B)# elementwise product
print("On the other hand, multiply two matrix is obtaine by A.dot(B)", A.dot(B))                    # another matrix product
#Note. Be care, with the matrix product. Remember that multiply a matrix MxN by other matrix NxZ, 
#you will obtained a matriz result with MxZ size.

The multiplicacion between each element by ohter element in different matrices is obtained by A * B [[2 0]
 [0 4]]
On the other hand, multiply two matrix is obtaine by A.dot(B) [[5 4]
 [3 4]]


In [26]:
print("The rest of matrix A-B is", A-B)
#This elevate each element to 2 to elevate each element inside the matrix,
#you should use double ** and add the potentiation number 
print("This elevate each element to 2", B**2)

The rest of matrix A-B is [[-1  1]
 [-3 -3]]
This elevate each element to 2 [[ 4  0]
 [ 9 16]]


Summarize, Numpy is a tool very useful to manage and operate numeric matrix data